AllCops:
  Exclude:
    - napakalaki.gemspec

Documentation:
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: true