module CombatResult
  WINANDWINGAME = :WINANDWINGAME
  WIN = :WIN
  LOSE = :LOSE
  LOSEANDESCAPE = :LOSEANDESCAPE
  LOSEANDDIE = :LOSEANDDIE
  LOSEANDCONVERT = :LOSEANDCONVERT
end

module Model

end

Model::CombatResult = CombatResult